version: "3.7"
services:
 web:
  image: nginx
  volumes:
   - /var/www/hello-world-vue:/usr/share/nginx/html
  restart: always
  build: .
  ports:
  - "8080:80"
  environment:
  - NGINX_HOST=foobar.com
  - NGINX_PORT=80          